import { Shield, Mail, ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';

export function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-[#473472] py-12 px-4 sm:px-6">
      <div className="max-w-4xl mx-auto">
        {/* Navigation */}
        <div className="mb-8">
          <Link 
            to="/" 
            className="inline-flex items-center gap-2 px-6 py-3 rounded-2xl bg-[#53629E]/20 text-[#87BAC3] font-bold hover:bg-[#D6F4ED] hover:text-[#473472] transition-all"
          >
            <ArrowLeft size={18} /> Back to Home
          </Link>
        </div>

        {/* Header Section */}
        <div className="text-left mb-12 border-b border-[#53629E]/30 pb-12">
          <h1 className="text-5xl font-black text-[#D6F4ED] tracking-tight mb-4 flex items-center gap-4">
            <Shield size={48} className="text-[#87BAC3]" /> Privacy Policy
          </h1>
          <p className="text-[#87BAC3] text-sm font-bold uppercase tracking-widest opacity-80 mt-6">
            Last updated: April 03, 2026
          </p>
        </div>

        {/* Professional Content */}
        <div className="space-y-12 text-[#D6F4ED]/90 leading-relaxed font-medium">
          
          <section className="bg-[#53629E]/10 p-8 rounded-3xl border border-[#53629E]/20">
            <p className="mb-6">
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p>
              We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the TermsFeed Privacy Policy Generator.
            </p>
          </section>

          <section>
            <h2 className="text-3xl font-black text-[#D6F4ED] mb-6">Interpretation and Definitions</h2>
            <div className="space-y-6">
              <div>
                <h3 className="text-[#87BAC3] text-xl font-bold mb-3">Interpretation</h3>
                <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
              </div>
              <div>
                <h3 className="text-[#87BAC3] text-xl font-bold mb-3">Definitions</h3>
                <p className="mb-4">For the purposes of this Privacy Policy:</p>
                <ul className="space-y-4 list-none p-0">
                  <li className="pl-6 border-l-2 border-[#87BAC3]/30"><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                  <li className="pl-6 border-l-2 border-[#87BAC3]/30"><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to indie.backseat.</li>
                  <li className="pl-6 border-l-2 border-[#87BAC3]/30"><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                  <li className="pl-6 border-l-2 border-[#87BAC3]/30"><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                  <li className="pl-6 border-l-2 border-[#87BAC3]/30"><strong>Service</strong> refers to the Website.</li>
                  <li className="pl-6 border-l-2 border-[#87BAC3]/30"><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                  <li className="pl-6 border-l-2 border-[#87BAC3]/30"><strong>Website</strong> refers to indie.backseat, accessible from https://www.indie.backseat.com.</li>
                </ul>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-3xl font-black text-[#D6F4ED] mb-6">Collecting and Using Your Personal Data</h2>
            <div className="space-y-6">
              <div>
                <h3 className="text-[#87BAC3] text-xl font-bold mb-3">Types of Data Collected</h3>
                <h4 className="text-[#D6F4ED] font-bold mb-2">Personal Data</h4>
                <p className="mb-4">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: <strong>Email address</strong>.</p>
                
                <h4 className="text-[#D6F4ED] font-bold mb-2 mt-6">Usage Data</h4>
                <p>Usage Data is collected automatically when using the Service. It may include information such as Your Device's IP address, browser type, browser version, the pages of our Service that You visit, and other diagnostic data.</p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-3xl font-black text-[#D6F4ED] mb-6">Tracking Technologies and Cookies</h2>
            <p className="mb-4">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.</p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-8">
              <div className="p-6 rounded-3xl bg-[#53629E]/10 border border-[#53629E]/20">
                <h4 className="text-[#87BAC3] font-black mb-2">Session Cookies</h4>
                <p className="text-sm">These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features.</p>
              </div>
              <div className="p-6 rounded-3xl bg-[#53629E]/10 border border-[#53629E]/20">
                <h4 className="text-[#87BAC3] font-black mb-2">Functionality Cookies</h4>
                <p className="text-sm">These Cookies allow Us to remember choices You make when You use the Website, such as remembering your login details.</p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-3xl font-black text-[#D6F4ED] mb-6">Retention of Your Personal Data</h2>
            <p className="mb-6">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations.</p>
            <div className="bg-[#D6F4ED]/5 p-6 rounded-3xl border border-[#D6F4ED]/10">
              <ul className="space-y-4 text-sm">
                <li><strong>User Accounts:</strong> retained for the duration of your account relationship plus up to 24 months.</li>
                <li><strong>Usage Data:</strong> up to 24 months from the date of collection.</li>
                <li><strong>Server logs:</strong> up to 24 months for security monitoring.</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-3xl font-black text-[#D6F4ED] mb-6">Delete Your Personal Data</h2>
            <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may update, amend, or delete Your information at any time by signing in to Your Account and visiting the settings section.</p>
          </section>

          <section className="bg-[#53629E]/10 p-8 rounded-3xl border border-[#53629E]/20">
            <h2 className="text-3xl font-black text-[#D6F4ED] mb-6">Contact Us</h2>
            <p className="mb-8 font-bold text-[#87BAC3]">If you have any questions about this Privacy Policy, You can contact us:</p>
            <Link 
              to="/contact" 
              className="inline-flex items-center gap-3 px-8 py-4 rounded-2xl bg-[#87BAC3] text-[#473472] font-black hover:bg-[#D6F4ED] transition-all shadow-xl shadow-[#87BAC3]/10"
            >
              <Mail size={20} /> Contact Us
            </Link>
          </section>
        </div>

        <div className="mt-20 pt-12 border-t border-[#53629E]/30 text-center">
          <p className="text-[#87BAC3]/60 text-xs font-bold uppercase tracking-widest">
            © 2026 indie.backseat. All rights reserved.
          </p>
        </div>
      </div>
    </div>
  );
}
